% === Requirements ===
% As per ASC2022 10.5.C:
% Solar cars must be able to repeatedly stop from speeds of 
% 50 km/h (31 mph) or greater, with an average deceleration, on 
% level wetted pavement, exceeding 4.72 m/s^2.
%
% For buffer velocity = 60km/h and deceleration = 6 m/s^2.


% === Design Parameters ===
m = 500;    %Mass of the vehicle (kg)
v = 60;     %Velocity of moving vehicle (km/h)

F_d = 130;  %Force applied to the pedal pad by the driver (N)
L_1 = 0.1;  %distance from the brake pedal arm pivot to the output rod clevis attachment (m)
L_2 = 0.51;  %distance from the brake pedal arm pivot to the brake pedal pad (m)

MC_Bore = 0.0158;          %(m)
A_mc = pi*(MC_Bore)^2/4;    %Effective area of the master cylinder (m^2)
A_cal = 0.001935;           %(m^2)

CG_f = 1.47;    %Distance between front axle to CG (m)
CG_r = 1.47;    %Distance between rear axle to CG (m)
WB = 2.94;      %Distance between front axle to rear axle (m)
h_cg = 0.5775;  %Height of Centre of gravity (m)
g = 9.8;        %Gravity (N/kg)
V_t = m*g;      %Weight of the vehicle(N)

R_eff_f = 0.3048;   %Effective rolling radius/Effective radius (effective moment arm) 
R_eff_r = 0.3048;   %of the rotor (measured from the rotor centre of rotation to the 
                    %centre of pressure of the caliper pistons) (m)
R_t = 0.254;
u_bp = 0.4;     %Coefficient of friction between the brake pad and the rotor 
u_peak_f = 0.6; %Maximum effective coefficient of friction between the front tires and the road 
u_peak_r = 0.6; %Maximum effective coefficient of friction between the rear tires and the road


% === Calculations ===
% --- Brake Pedal Force (F_bp) --- 
F_bp = F_d * (L_2 / L_1);   %Force output of the brake pedal assembly (N)

% --- Master Cylinder Pressure --- 
P_mc = F_bp / A_mc;         %Hydraulic pressure generated by the master cylinder (Pa)

% --- Force generated by caliper piston --- 
P_cal = P_mc;               %Hydraulic pressure transmitted to the calliper (Pa)
F_cal = P_cal * A_cal;      %One-sided linear mechanical force generated by the caliper (N)

% --- Caliper Clamp Load --- 
F_cl = F_cal * 2;           %Clamp force generated by the caliper (N)

% --- Force on disc by brake pads --- 
F_friction = F_cl * u_bp;   %Frictional force generated by the brake pads opposing the rotation of the rotor (N)

% --- Torque of rotor --- 
T_r_f = F_friction * R_eff_f;   %Torque generated by the rotor (N*m)
T_r_r = F_friction * R_eff_r;

% --- Force on a tire --- 
F_tire_f = T_r_f / R_t;         %Force reacted between the tire and the ground (assuming friction exists to support the force) (N)
F_tire_r = T_r_r / R_t;
F_total = F_tire_f * 2 + F_tire_r * 2;  %Total braking force reacted between the vehicle and the ground (assuming adequate traction exists) (N)

% --- Kinetic energy of the vehicle --- 
v = v / 3.6;        %km/h to m/s
KE = (1/2)*m*v^2;   %(J)

% --- Stopping Distance --- 
d_s = KE / (u_peak_f * m * g);  %Stopping distance of the vehicle (m)

% --- Deceleration --- 
a_v = (0^2 - v^2) / (2 * d_s);  %Deceleration of the vehicle (m/s^2)

% --- Front axle vertical force --- 
V_f = (CG_f * V_t) / WB;    %(N)

% --- Rear axle vertical force --- 
V_r = (CG_r * V_t) / WB;    %(N)

% --- Dynamic absolute weight transferred --- 
WT = abs((a_v / g) * (h_cg / WB) * V_t);  %Absolute weight transferred from the rear axle to the front axle (N) 

% --- Dynamic Vertical Force --- 
V_f_d = V_f + WT;   %Front axle dynamic vertical force for a given deceleration (N)
V_r_d = V_r - WT;   %Rear axle dynamic vertical force for a given deceleration (N)

% --- Effect of weight transfer on Tire Output --- 
F_tire_f_wt = u_peak_f * V_f;       %(N)
F_tire_r_wt = u_peak_r * V_f;

% --- Maximum Braking Force Produced By axle --- 
F_tire_f_bf = u_peak_f * V_f_d;     %(N)
F_tire_r_bf = u_peak_r * V_r_d;

% --- Breaking Efficiency --- 
n = (F_total / V_t) * 100;

