%% === Requirements ===
% As per ASC2022 10.5.C:
% Solar cars must be able to repeatedly stop from speeds of 
% 50 km/h (31 mph) or greater, with an average deceleration, on 
% level wetted pavement, exceeding 4.72 m/s^2.
%
% For buffer velocity = 60km/h and deceleration = 6 m/s^2.
ASC_Requirement = 4.72;     %Average deceleration (m/s^2)


%% === Vehicle Parameters ===
% -- Constants ---
g = 9.8;        %Gravity (N/kg)

% --- Mass/Weight ---
m = 500;    %Mass of the vehicle (kg)
V_t = m*g;      %Weight of the vehicle(N)

v = 60;     %Velocity of moving vehicle (km/h)

% --- Brake Pedal ---
F_d = 130;    %Force applied to the pedal pad by the driver (N)
L_ratio = 7;  %L2/L1
%L_1 = 0.1;   %Distance from the brake pedal arm pivot to the output rod clevis attachment (m)
%L_2 = 0.51;  %Distance from the brake pedal arm pivot to the brake pedal pad (m)

% --- Master Cylinder ---
MC_Bore = 1;                    %(Inch)
A_mc = pi*(MC_Bore/39.37)^2/4;  %Effective area of the master cylinder (m^2)
A_cal_f = 0.001019353;          %Front (m^2)
A_cal_r = 0.00154838;          %Rear (m^2)

% --- Axle Distance ---
CG_f = 1.47;    %Distance between front axle to CG (m)
CG_r = 1.47;    %Distance between rear axle to CG (m)
WB = 2.94;      %Distance between front axle to rear axle (m)
h_cg = 0.5775;  %Height of Centre of gravity (m)

% --- Rolling Resistance/Friction ---
R_eff_f = 0.26/2;   %Effective rolling radius/Effective radius (effective moment arm) 
R_eff_r = 0.3302/2;   %of the rotor (measured from the rotor centre of rotation to the 
                    %centre of pressure of the caliper pistons) (m)
R_t = 0.254;
u_bp = 0.4;     %Coefficient of friction between the brake pad and the rotor 
u_peak_f = 0.6; %Maximum effective coefficient of friction between the front tires and the road 
u_peak_r = 0.6; %Maximum effective coefficient of friction between the rear tires and the road


%% === Calculations ===
% --- Brake Pedal Force (F_bp) --- 
F_bp = F_d * L_ratio;   %Force output of the brake pedal assembly (N)

% --- Master Cylinder Pressure --- 
P_mc = F_bp / A_mc;         %Hydraulic pressure generated by the master cylinder (Pa)

% --- Force generated by caliper piston --- 
P_cal = P_mc;                   %Hydraulic pressure transmitted to the calliper (Pa)
F_cal_f = P_cal * A_cal_f;      %One-sided linear mechanical force generated by the caliper (N)
F_cal_r = P_cal * A_cal_r;

% --- Caliper Clamp Load --- 
F_cl_f = F_cal_f * 2;           %Clamp force generated by the caliper (N)
F_cl_r = F_cal_r; 

% --- Force on disc by brake pads --- 
F_friction_f = F_cl_f * u_bp;   %Frictional force generated by the brake pads opposing the rotation of the rotor (N)
F_friction_r = F_cl_r * u_bp;

% --- Torque of rotor --- 
T_r_f = F_friction_f * R_eff_f; %Torque generated by the rotor (N*m)
T_r_r = F_friction_r * R_eff_r;

% --- Force on a tire --- 
F_tire_f = T_r_f / R_t;         %Force reacted between the tire and the ground (assuming friction exists to support the force) (N)
F_tire_r = T_r_r / R_t; % **Is R_eff_r in excel document**
F_total = F_tire_f * 2 + F_tire_r * 2;  %Total braking force reacted between the vehicle and the ground (assuming adequate traction exists) (N)

% --- Kinetic energy of the vehicle --- 
v = v / 3.6;        %km/h to m/s
KE = (1/2)*m*v^2;   %(J)

% --- Stopping Distance --- 
d_s = KE / (u_peak_f * m * g);  %Stopping distance of the vehicle (m)

% --- Deceleration --- 
a_v = (0^2 - v^2) / (2 * d_s);  %Deceleration of the vehicle (m/s^2)

% --- Front axle vertical force --- 
V_f = (CG_f * V_t) / WB;    %(N)

% --- Rear axle vertical force --- 
V_r = (CG_r * V_t) / WB;    %(N)

% --- Dynamic absolute weight transferred --- 
WT = abs((a_v / g) * (h_cg / WB) * V_t);  %Absolute weight transferred from the rear axle to the front axle (N) 

% --- Dynamic Vertical Force --- 
V_f_d = V_f + WT;   %Front axle dynamic vertical force for a given deceleration (N)
V_r_d = V_r - WT;   %Rear axle dynamic vertical force for a given deceleration (N)

% --- Effect of weight transfer on Tire Output --- 
F_tire_f_wt = u_peak_f * V_f;       %(N)
F_tire_r_wt = u_peak_r * V_r;

% --- Maximum Braking Force Produced By axle --- 
F_tire_f_bf = u_peak_f * V_f_d;     %(N)
F_tire_r_bf = u_peak_r * V_r_d;

% --- Breaking Efficiency --- 
n = (F_total / V_t) * 100;                      %Total
n_f = ((2 * F_tire_f / V_t * 100) / n) * 100;   %Front
n_r = ((2 * F_tire_r / V_t * 100) / n) * 100;   %Rear

% --- Theoretical Deceleration ---
Theoretical = F_total / m;
Difference = Theoretical - ASC_Requirement;
Safety_Factor = Theoretical / ASC_Requirement;

%% === Print Output ===
disp("ASC Requirement = " + ASC_Requirement + " m/s^2");
disp("Theoretical Deceleration = " + Theoretical + " m/s^2");
disp("Difference = " + Difference);
disp("Safety_Factor = " + Safety_Factor);
